steps:
- name: node
  entrypoint: npm
  args: ['install']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - myWebsiteBackend
  - --source=.
  - --trigger-http
- name: node
  entrypoint: npm
  args: ['test']
  env:
    - 'URL=${_MY_DEPLOYED_URL}'