version: "3"
services:
  postman_collection:
      container_name: postman_docker_container
      build: .
      image: postman_docker_image
      command:
        run collections/collection.json 
        -e environment/environment.json
        -r html,cli
        --reporter-html-export reports/Main_Report.html
      volumes:
        - ./:/etc/newman